In [1]:
#Importig library
import numpy as np

# CREATING ARRAY

In [2]:
#Creating array on various data type
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]) #Integer
arr2 = np.array(['a','b','c','d','e']) #String
arr3 = np.array([1.0,2.0,3.0,4.0,5.0,6.0]) #Float
arr4 = np.array([True, False, True, True, False]) #Boolean

#Array should have the same data type while creating array

In [3]:
#Printing the result
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10]
['a' 'b' 'c' 'd' 'e']
[1. 2. 3. 4. 5. 6.]
[ True False  True  True False]


# CONVERTING LIST INTO ARRAY

In [4]:
#Creating list 
nums = [1,2,3]

In [5]:
#Converting pyhton list into numpy array
nums = np.array(nums)

In [6]:
#View the result
nums

array([1, 2, 3])

# CREATING 2D ARRAY

In [7]:
#Creating list 
nums1 = [[1,2,3],[4,5,6]]

In [8]:
#Converting pyhton list into numpy array
nums1 = np.array(nums1)

In [9]:
#View the result
nums1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#Creating 2D array
nums_x = np.array([[1,2,3],[4,5,6]])

In [11]:
#Printing the result
nums_x

array([[1, 2, 3],
       [4, 5, 6]])

# CREATING 3D ARRAY

In [12]:
#Creating list 
nums2 = [[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]

In [13]:
#Converting pyhton list into numpy array
nums2 = np.array(nums2)

In [14]:
#View the result
nums2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
#Creating 3D array
num_y = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

In [16]:
#View the result
num_y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
#Creating 3D array
num_yx = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]],
                 [[13,14,15],[16,17,18]]])

In [18]:
num_yx

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

# VIEW THE DIMENSION AND SHAPE OF THE ARRAY

In [19]:
#View array dimension
print(nums.ndim)  #1D
print(nums1.ndim) #2D
print(nums2.ndim) #3D
print(num_y.ndim)
print(num_yx.ndim)

1
2
3
3
3


In [20]:
print(nums.shape)  #1 rows, no column
print(nums1.shape) #2 rows & 3 columns
print(nums2.shape) # 2 rows, 2 rows & 3 columns
print(num_yx.shape)

(3,)
(2, 3)
(2, 2, 3)
(3, 2, 3)


# NATURE OF ARRAY

In [21]:
#First two data are integer & last one is float
nums = [1,2,3.0] #Creating list
nums = np.array(nums) #Converting list into array
nums #View the result
#All the data become float if one data have float in array

array([1., 2., 3.])

In [22]:
#First two data are integer & last one is string
nums = [1,2,'3'] #Creating list
nums = np.array(nums) #Converting list into array
nums #View the result
#All the data become string if one data have string in array

array(['1', '2', '3'], dtype='<U11')

In [23]:
#Check data type
nums.dtype

dtype('<U11')