# CHECKING DATA TYPE OF AN ARRAY

In [1]:
#Importing library
import numpy as np

In [2]:
#Data Type in Numpy
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n'

In [6]:
#Creating an array
arr = np.array([1,2,3,4,5,6,7]) #Integer
arr
arr1 = np.array(['Bhavik','Amit','Vikas']) #String
arr1
arr2 = np.array([1.25,6.357,8.745,6.10]) #Float
arr2

array([1.25 , 6.357, 8.745, 6.1  ])

In [10]:
#Checking the type of an array
print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

int32
<U6
float64


# CREATING ARRAY WITH DEFINED DATA TYPE

In [27]:
#Creating array with string defined
arr = np.array([1,2,3,4], dtype = 'S')
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [28]:
#Checking the data type
arr.dtype

dtype('S1')

In [29]:
#Creating array with float defined
arr1 = np.array([1,2,3,4], dtype = 'f')
arr1

array([1., 2., 3., 4.], dtype=float32)

In [21]:
#Checking the data type
arr1.dtype

dtype('float32')

In [30]:
#Creating array with integer defined
arr2 = np.array([1,2,3,4], dtype = 'i')
arr2

array([1, 2, 3, 4], dtype=int32)

In [31]:
#Checking the data type
arr2.dtype

dtype('int32')

# VALUE ERROR WHILE CONVERTING

In [32]:
#Creating array with integer defined
arr3 = np.array(['a','2','3','4'], dtype = 'i')
arr3

ValueError: invalid literal for int() with base 10: 'a'

# CONVERTING ONE ARRAY DATA TYPE INTO ANOTHER ARRAY DATA TYPE

In [33]:
#Creating array
arr4 = np.array([1,2,3,4])
arr4

array([1, 2, 3, 4])

In [34]:
#Checking data type
arr4.dtype
#This is an integer

dtype('int32')

In [35]:
#Converting data type integer into string
arr5 = arr4.astype('S')
arr5

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [36]:
#Creating array 
arr4 = np.array([1.5,2.6,3.8,4.1])
arr4

array([1.5, 2.6, 3.8, 4.1])

In [37]:
#Checking data type
arr4.dtype
#This is a float

dtype('float64')

In [38]:
#Converting data type float into integer
arr5 = arr4.astype('i')
arr5

array([1, 2, 3, 4], dtype=int32)

In [ ]:
#Creating array 
arr4 = np.array([1.5,2.6,3.8,4.1])
arr4

In [40]:
#Converting data type float into integer
arr6 = arr4.astype(bool)
arr6

array([ True,  True,  True,  True])