In [1]:
#Import library
import numpy as np

# ZEROS FUNCTION

In [2]:
#Creating 0(Zero) array
arr = np.zeros(5) #Five times zero
arr

array([0., 0., 0., 0., 0.])

In [3]:
#Creating 0(Zero) array in number of rows
arr1 = np.zeros((2,3)) # Three time zero in two rows
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Creating 0(Zero) array in number of rows
arrx = np.zeros((5,5)) # Three time zero in two rows
arrx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#Creating 0(Zero) array in number of rows using squre bracket
arry = np.zeros([5,5])
arry

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ONES FUNCTION

In [6]:
#Creating 1(One) in array
arr2 = np.ones((2,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#Creating 1(One) in array in number of rows
arr3 = np.ones(4)
arr3

array([1., 1., 1., 1.])

# EYE FUNCTION

In [8]:
#Creating diagonal 1 in array
arr4 = np.eye(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
#Creating diagonal 1 in 3 rows and 4 columns
arr5 = np.eye(3,4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
#Creating diagonal 1 in 1 rows and 4 columns
arra = np.eye(1,4)
arra

array([[1., 0., 0., 0.]])

In [11]:
##Creating diagonal 1 in 2 rows and 4 columns
arrb = np.eye(2,4)
arrb

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [14]:
##Creating diagonal 1 in 10 rows and 10 columns
arrc = np.eye(10,10)
arrc

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# DIAG FUNCTION 

In [22]:
#Creating diagonal from 1 to 4
arr6 = np.diag([1,2,3,4])
arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
#Finding the diagonal array
np.diag(arr6)

array([1, 2, 3, 4])

In [24]:
#Creating diagonal from 1 to 15
arr7 = np.diag([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr7

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [25]:
#Finding the diagonal array
np.diag(arr7)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# RANDINT FUNCTION

In [26]:
#Creating 4 random numbers from the range from 1 to 15 (exclusing last number)
random = np.random.randint(1,15,4)
random

array([9, 5, 8, 5])

In [27]:
#Creating 50 random numbers from the range from 1 to 1000 (exclusing last number)
random1 = np.random.randint(1,1000,50)
random1

array([401, 431, 817, 268, 893, 647, 185,  57, 219, 654, 112, 781, 533,
       104, 157, 166, 513, 983, 889, 758, 636, 659, 493,  97,  17, 553,
       975, 493, 676,  80, 137, 531, 767, 969, 472, 741, 524, 127, 113,
       801, 349, 538, 366,  85, 360, 731, 596, 738, 637, 468])

# RAND FUNCTION

In [29]:
#Creating random number which are range between 0 to 1
random2 = np.random.rand(10)
random2

array([0.631807  , 0.349886  , 0.91116861, 0.69316865, 0.34070388,
       0.86191855, 0.52885233, 0.36962359, 0.26146984, 0.10295685])

In [32]:
#Crearting 2D array have random number which are range between 0 to 1
random3 = np.random.rand(6,3)
random3

array([[0.29472559, 0.36560471, 0.07696672],
       [0.59669699, 0.49516387, 0.27630399],
       [0.74361659, 0.46562319, 0.86113517],
       [0.49267876, 0.38722426, 0.26577638],
       [0.79934963, 0.7696401 , 0.06048848],
       [0.81365924, 0.11504671, 0.01086511]])

# RANDN FUNCTION

In [33]:
#Creating array have random numbers of standard normal distribution
random4 = np.random.randn(4)
random4

array([ 0.30967775,  1.37756612, -0.09623213, -0.86502461])

In [34]:
#Creating array have random numbers of standard normal distribution
random5 = np.random.randn(500)
random5

array([ 2.81279353e-01,  1.48728808e+00, -5.01738199e-01,  3.76309994e-01,
       -1.88693062e-01,  1.31349859e+00, -2.77590964e-02,  6.19571562e-01,
       -3.99675575e-01, -4.43600298e-01,  7.78717422e-01, -8.13472941e-01,
       -1.71532744e+00,  1.87684708e+00,  4.94827780e-02, -1.51477354e+00,
        1.85809838e+00, -1.28262990e+00,  1.64967316e-01,  7.64121095e-01,
       -1.06420616e+00, -9.61174755e-01, -1.50885490e+00,  1.03268824e+00,
        5.21108352e-01,  1.45570761e-01, -1.07668491e+00, -1.26353096e+00,
        1.19361201e+00,  1.36784865e-01,  1.08921341e+00,  7.74806170e-01,
       -5.72964501e-01, -2.79233958e-01,  8.90531768e-01, -5.73211711e-01,
       -7.89774001e-01,  7.36161089e-01, -7.15268472e-01,  2.45662075e-01,
       -1.15379739e+00,  2.48379691e+00,  6.44580679e-01,  8.80206660e-02,
        1.67969165e-01, -1.23063000e+00,  1.82587830e+00,  3.61029667e-01,
        1.24079807e+00,  2.02084625e-01, -1.65808415e+00,  2.18003589e+00,
        2.00862686e+00, -

In [35]:
#Computing mean of an array random5
np.mean(random5)

-0.050687703839245854