# -1 IN COLUMN WHILE RESHAPE OF AN ARRAY(Negative One Leakage)

In [1]:
#Importing library
import numpy as np

In [2]:
#Creating numbers from 1 to 11
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Reshaping of 1D into 2D
arr.reshape(2,-1)

#10 / 2 = 5 i.e 5 numbers on each array
#Numpy will not consider -1 in column and it will autometically calculate how many numbers will set in each array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
#Reshaping of 1D into 
arr.reshape(5,-1)

#10 / 5 = 2 i.e 2 numbers on each array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# -1 IN ROWS WHILE RESHAPE OF AN ARRAY

In [5]:
#Creating numbers from 1 to 110
arr1 = np.arange(1,111)
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [8]:
#Reshaping of 1D into 2D
arr1.reshape(-1,5)

#Total numbers in 1D array is 110
#Total columns to be set in numbers are 5

#110 / 5 = 22 i.e. 22 rows require and each rows have 5 numbers
#Numpy will not consider -1 in rows and it will autometically calculate how many rows will set for each array

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

In [10]:
#Reshaping of 1D into 2D
arr1.reshape(23,-1)

#Here Numpy unable to reshape of an array due to 110 not be able to get with the number 23

ValueError: cannot reshape array of size 110 into shape (23,newaxis)