In [1]:
#Importing library
import numpy as np

In [8]:
#Generating random numbers
arr = np.random.randint(1,101,50)
arr
#Every time I press enter, the numbers are change due to which I am not be able to generate same random number again & again

array([ 69, 100,   3,  41,  42,   7,  98,  92,  26,  29,  28,  11,  67,
        42,  97,  98,  80,  67,   5,  85,  54,  52,  46,  50,  81,  31,
        18,  25,  90,  98,  83,  31,  17,  36,  90,  66,  12,  94,  52,
        45,  27,  80,  88,  60,   4,  74,  47,  62,  69,  49])

In [22]:
#Fixing the reproduction of random number
np.random.seed(123)
arr1 = np.random.randint(1,101,50)
arr1

array([ 67,  93,  99,  18,  84,  58,  87,  98,  97,  48,  74,  33,  47,
        97,  26,  84,  79,  37,  97,  81,  69,  50,  56,  68,   3,  85,
        40,  67,  85,  48,  62,  49,   8, 100,  93,  53,  98,  86,  95,
        28,  35,  98,  77,  41,   4,  70,  65,  76,  35,  59])

In [24]:
#Finding a size of an array
arr.size
#We have 50 random numbers in our array

50

In [27]:
#Fixing the reproduction of random number
np.random.seed(123)
#Creating 50 random numbers from the range 1 to 100 with 2D dimension
arr2 = np.random.randint(1,101,50).reshape(5,10)
arr2

#Five rows and 10 columns

array([[ 67,  93,  99,  18,  84,  58,  87,  98,  97,  48],
       [ 74,  33,  47,  97,  26,  84,  79,  37,  97,  81],
       [ 69,  50,  56,  68,   3,  85,  40,  67,  85,  48],
       [ 62,  49,   8, 100,  93,  53,  98,  86,  95,  28],
       [ 35,  98,  77,  41,   4,  70,  65,  76,  35,  59]])

In [28]:
#Finding a size of an array
arr2.size
#We have 50 random numbers in our array

50