# EXTRACTING THE ELEMENT THROUGH INDEXING

In [1]:
#Importing library
import numpy as np

In [2]:
#Creating array
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [7]:
#Extracting through index
arr[0]#Extract 5 number through index
arr[1]#Extract 10 number through index
arr[2]#Extract 15 number through index
arr[3]#Extract 20 number through index
arr[4]#Extract 25 number through index

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

5
10
15
20
25


In [8]:
#Extracting number through index
arr[5]
#Its getting an error due 5th number does not exist

IndexError: index 5 is out of bounds for axis 0 with size 5

# EXTRACTING THE ELEMENT THROUGH NEGATIVE INDEXING

In [9]:
#View the array
arr

array([ 5, 10, 15, 20, 25])

In [10]:
#Extract the numbers through negative indexing
print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])
print(arr[-5])

25
20
15
10
5


In [11]:
#Extract the numbers through negative indexing
print(arr[-6])
#Its getting an error due 5th number does not exist

IndexError: index -6 is out of bounds for axis 0 with size 5

# SLICING THE ELEMENT THROUGH INDEXING

In [12]:
#Extracting all the elements through indexing
arr[:]

array([ 5, 10, 15, 20, 25])

In [13]:
#Extracting all the elements through indexing
arr[0:4]

array([ 5, 10, 15, 20])

In [14]:
#Extract first thre numbers from an array
arr[:3]

array([ 5, 10, 15])

In [15]:
#Extract first thre numbers from an array
arr[0:3]

array([ 5, 10, 15])

In [16]:
#Extract 3rd number to last number
arr[2:]

array([15, 20, 25])

In [18]:
#Extract 3rd number to last number
arr[2:5]

array([15, 20, 25])

# SLICING THE ELEMENT THROUGH NEGATIVE INDEXING

In [22]:
#View the array
arr

array([ 5, 10, 15, 20, 25])

In [21]:
#Extract 2nd, 3rd and 4th element through negative index
arr[-4:-1]

array([10, 15, 20])

In [32]:
#Extracting elements
print(arr[-5:])
print(arr[-5:-1])
print(arr[-5:-2])
print(arr[-5:-3])
print(arr[-5:-4])
print(arr[-5:-5])

[ 5 10 15 20 25]
[ 5 10 15 20]
[ 5 10 15]
[ 5 10]
[5]
[]


# STEP IN ARRAY

In [33]:
#View the array
arr

array([ 5, 10, 15, 20, 25])

In [35]:
#Step in 1 in array
arr[0:5:1]
#It takes all the elements due to no skipping of an elements

array([ 5, 10, 15, 20, 25])

In [36]:
#Step in 2 in array
arr[0:5:2]
#It skips 2nd element after one element

array([ 5, 15, 25])

In [37]:
#Step in 3 in array
arr[0:5:3]
#It skips 2nd & 3rd element after one element

array([ 5, 20])

# REVERSE STEP OF AN ARRAY

In [38]:
#Reverse all the array
arr[::-1]

array([25, 20, 15, 10,  5])

In [39]:
# Reverse the array after skip 2nd element
arr[::-2]

array([25, 15,  5])

In [41]:
# Reverse the array after skip 2nd & 3rd element
arr[::-3]

array([25, 10])

In [42]:
# Reverse the array after skip 2nd, 3rd & 4th element
arr[::-4]

array([25,  5])

# EXTRACTING ELEMENT THROUGH DOUBLE COLON

In [43]:
#Selecting all the element
arr[0::]

array([ 5, 10, 15, 20, 25])

In [44]:
#Selecting 2nd to last element
arr[1::]

array([10, 15, 20, 25])

In [45]:
#Selecting 3rd to last element
arr[2::]

array([15, 20, 25])

In [46]:
#Selecting 4th to last element
arr[3::]

array([20, 25])