In [1]:
#Importing library
import numpy as np

In [2]:
#Creating array
matrix = np.array([[5,10,15],
                  [20,25,30],
                  [35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# INDEXING USING DOUBLE BRACKET NOTATION

In [15]:
#Select each elements one by one
print(matrix[0][0]) #[Array index] [ Element Index]
print(matrix[0][1])
print(matrix[0][2])
print(matrix[1][0])
print(matrix[1][1])
print(matrix[1][2])
print(matrix[2][0])
print(matrix[2][1])
print(matrix[2][2])

#First bracket indicates array index and second bracket indicate element index

5
10
15
20
25
30
35
40
45


# INDEXING USING SINGLE BRACKET NOTATION

In [16]:
#View the matrix
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
#Select each elements one by one
print(matrix[0,0])
print(matrix[0,1])
print(matrix[0,2])
print(matrix[1,0])
print(matrix[1,1])
print(matrix[1,2])
print(matrix[2,0])
print(matrix[2,1])
print(matrix[2,2])

5
10
15
20
25
30
35
40
45


# SLICING USING SINGLE BRACKET NOTATION

In [25]:
#View the array
matrix
#0,1,2 ---0
#0,1,2 ---1
#0,1,2 ---2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
#Selecting 5,10,20,25 from above array
matrix[:2,:2]

#5,10 - Selecting 0 for first row
#20,25- Selecting 2 for second row
#5,20 - Selecting 0 for first column
#10,25 - Selecting 2 for second column

array([[ 5, 10],
       [20, 25]])

In [68]:
#Select 10,15,25,30
matrix[0:2,1:3]

#10,15 - Selecting 0 for first row
#25,30 - Selecting 2 for second row
#10,25 - Selecting 1 for first column
#15,30 - Selecting 3 for second column

array([[10, 15],
       [25, 30]])

In [69]:
#View array
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
#Selecting 20,25,35,40
matrix[1:3,0:2]

#20,25 - Selecting 1 for first row
#35,40 - Selecting 3 for second row
#20,35 - Selecting 0 for first column
#25,40 - Selecting 2 for second column

array([[20, 25],
       [35, 40]])

In [71]:
#Creating new matrix 5 by 5
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [72]:
#Extract number 47,97,26,37,97,81
matrix2[2:4,2:5]

#47,97,26 - Selecting 2 for 2nd row
#37,97,81 - Selecting 4 for 3rd row
#47,37,97,97 - Selecting 2 for 2nd column
#97,97,26,81 - Selecting 5 for 4th column

array([[47, 97, 26],
       [37, 97, 81]])