# VIEW OF AN ARRAY

In [6]:
#Import library
import numpy as np

In [14]:
#Creating array
arr = np.array([5,10,15,20,25,30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [8]:
#Slicing 15,20,25 numbers from array
sliced_array = arr[2:5]
sliced_array

array([15, 20, 25])

In [9]:
#Changing the all sliced array value to zero
sliced_array[:] = 0

In [10]:
#View sliced array
sliced_array

array([0, 0, 0])

In [11]:
#View original array
arr

array([ 5, 10,  0,  0,  0, 30])

#Here the value changed in sliced array, Original array value also changed.
#Sliced array is just a view of an array and this is a draw back for us. To overcome this issue, We will use copy function

# COPY OF AN ARRAY

In [15]:
#Slicing 15,20,25 numbers from array
sliced_array = arr[2:5].copy()
sliced_array

#Changing the all sliced array value to zero
sliced_array[:] = 0

In [17]:
#View the sliced array
print(sliced_array)
print(arr)

[0 0 0]
[ 5 10 15 20 25 30]
