In [4]:
#Importing library
import numpy as np

In [7]:
#Creating array
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
#array multiply by 2
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [9]:
#array addition by 5
arr + 5

array([ 6,  7,  8,  9, 10, 11])

In [10]:
#array exponentiation by 4
arr ** 4

array([   1,   16,   81,  256,  625, 1296], dtype=int32)

In [12]:
#Creating array with 2 by 3 matrix
arr1 = np.array([1,2,3,4,5,6]).reshape(3,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#Operations on array
print(arr1*2)#Multiply
print(arr1+5)#Addition
print(arr1**4)#Exponentiation
print(arr1/2)#Division

[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[   1   16]
 [  81  256]
 [ 625 1296]]
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [14]:
# 1 is divisible by 0
1/0
#It is showing an error

ZeroDivisionError: division by zero

In [16]:
#array values divisible by 0
arr1/0
# it will not show an error as it shows only warning

<ipython-input-16-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf],
       [inf, inf],
       [inf, inf]])