In [1]:
#Importing library
import numpy as np

In [2]:
#Creating array
arr1 = np.array([1,2,3,4])
print(arr1)
arr2 = np.array([5,6,7,8])
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [3]:
#Addition of two arrays
arr1 + arr2

array([ 6,  8, 10, 12])

In [5]:
#Multiplication of two arrays
arr1 * arr2

array([ 5, 12, 21, 32])

In [6]:
#Division of two arrays
arr1 / arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [10]:
#Exponentiation of two arrays
arr1 ** arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [8]:
#Creating array
arr3 = np.array([1,2,3,4])
print(arr3)
arr4 = np.array([5,6,7])
print(arr4)

[1 2 3 4]
[5 6 7]


In [9]:
#Addition of two arrays
arr3 + arr4
#This is operation unable to perform due to both arrays element are not equals

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
#Creating another array
arr5 = np.array([9,10,11,12])

#View all arrays
print(arr1)
print(arr2)
print(arr5)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [14]:
#Exponentiation & addition
arr1**arr2+arr5

array([   10,    74,  2198, 65548])

In [16]:
#Division & addition
arr1/arr2+arr5

array([ 9.2       , 10.33333333, 11.42857143, 12.5       ])

In [28]:
#Creating matrix
np.random.seed(123)

matrix1 = np.random.randint(1,12,9).reshape(3,3)

matrix2 = np.random.randint(5,15,9).reshape(3,3)

In [29]:
#View matrix1
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [30]:
#View matrix2
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [31]:
#Addition of two matrix
matrix1 + matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [32]:
#Creating matrix
np.random.seed(123)

matrix3 = np.random.randint(1,12,10).reshape(2,5)

matrix4 = np.random.randint(5,15,9).reshape(3,3)

In [33]:
#Addition of two matrix
matrix3+ matrix4
#It is showing an error due both matrix are not same size

ValueError: operands could not be broadcast together with shapes (2,5) (3,3) 

In [34]:
#Matrix multiplication in school
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])