In [1]:
#Importing library
import numpy as np

In [2]:
#Creating an array
arr = np.array([2,80,1,97,5])
arr

array([ 2, 80,  1, 97,  5])

In [3]:
#Finding minimum value
np.min(arr)

1

In [4]:
#Finding maximum value
np.max(arr)

97

In [5]:
#Finding position of minimum value
np.argmin(arr)
#Minimum value has placed on 2nd position

2

In [7]:
#Finding position of maximum value
np.argmax(arr)
#Maximum value has placed on 3rd position

3

In [8]:
#Computing square root of an array
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [9]:
#Computing exponentiation
np.exp(arr)
#It will calculate euler number 2.7182818284590452353602874713527 power of each numbers in array

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [11]:
#Mathametical computation for checking
print(2.7182818284590452353602874713527**2)
print(2.7182818284590452353602874713527**80)
print(2.7182818284590452353602874713527**1)
print(2.7182818284590452353602874713527**97)
print(2.7182818284590452353602874713527**5)

7.3890560989306495
5.540622384393487e+34
2.718281828459045
1.3383347192042626e+42
148.41315910257657


In [12]:
#Computing sin
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [13]:
#Computing cos
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [14]:
#Computing tan
np.tan(arr)

array([-2.18503986,  9.00365495,  1.55740772, -0.4103213 , -3.38051501])

In [15]:
#From 1 to 15 range of a number require 50 numbers
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [16]:
#From 1 to 50 range of a number require 5 numbers
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [17]:
#Creating an array
arr2 = np.array([1,2,3,0])
arr2

array([1, 2, 3, 0])

In [18]:
#Creating array and defining the data type bool
arr2 = np.array([1,2,3,0],dtype = 'bool')
arr2

array([ True,  True,  True, False])

In [19]:
#Creating array and defining the data type float
arr2 = np.array([1,2,3,0],dtype = 'float')
arr2

array([1., 2., 3., 0.])

In [22]:
#Creating array and defining the data type string
arr2 = np.array([1,2,3,0],dtype = 'str')
arr2

array(['1', '2', '3', '0'], dtype='<U1')

In [25]:
#Creating array and defining the data type string
arr3 = np.array([0,1,0,1,1,1,0,0,1],dtype = 'bool')
arr3

array([False,  True, False,  True,  True,  True, False, False,  True])

In [27]:
#Using for loop in array
for i in arr3:
    print(i)

False
True
False
True
True
True
False
False
True
