In [1]:
#Importing library
import numpy as np

In [16]:
#Creating array
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)
matrix

matrix1 = np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[ 2, 10,  1],
       [ 1, 10,  4],
       [ 5,  1,  1]])

In [3]:
#Sum of matrix
matrix.sum()

39

In [4]:
#Min in matrix
np.min(matrix)

1

In [5]:
#Max in matrix
np.max(matrix)

10

In [6]:
#Getting row wise min
np.min(matrix, axis = 1)

array([3, 2, 1])

In [7]:
#Getting row wise max
np.max(matrix, axis = 1)

array([ 7, 10,  7])

In [8]:
#Getting sum row wise
np.sum(matrix, axis = 1)

array([13, 16, 10])

In [9]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [10]:
#Cumlative sum of array
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [11]:
#Cumlative sum of array column wise
np.cumsum(matrix, axis = 0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [12]:
#Cumlative sum of array row wise
np.cumsum(matrix, axis = 1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [13]:
#Computing product row wise
np.prod(matrix, axis = 1)

array([63, 80, 14])

In [14]:
#Computing product column wise
np.prod(matrix, axis = 0)

array([42, 24, 70])

In [17]:
#Computing dot product
matrix.dot(matrix1)

array([[44, 67, 22],
       [58, 70, 28],
       [21, 91, 16]])