In [1]:
#Importing library
import numpy as np

In [2]:
#Creating an array
np.random.seed(123)
arr = np.random.randint(1,15,15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [3]:
#Shuffling the element in a list
np.random.shuffle(arr)

In [4]:
#View the array
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [10]:
#Finding unique values
np.unique(arr)
#It element repeated values and showing unique value

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [11]:
#To know the size of an element
np.unique(arr).size

10

In [12]:
#Checking size of an array or number of elements in array
arr.size

15

In [13]:
#Getting Unique elements with index number and counts
np.unique(arr, return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 9,  5,  0,  4,  1,  2,  6, 12, 14, 10], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))