In [1]:
#Importing library
import numpy as np

In [2]:
#Creating strings
array1 = np.array([1,2,3,4,5,6,7,8,9,10])

#Splitting 1 array into 5 arrays 
np.split(array1,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [11]:
#Creating strings
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
print(array2)

#Splitting array rows wise
np.split(array2,2,axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [12]:
#Creating strings
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
print(array2)

#Splitting array column wise
np.split(array2,2,axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [14]:
#Splitting 1D array into multiple arrays
np.split(array1, [1,4])

[array([1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10])]